name: proyecto-ml

volumes:
  airflow_data:

services:
  airflow-init:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    image: proyecto-ml-airflow:latest
    entrypoint: /bin/bash
    command:
      - -c
      - |
        echo "Inicializando base de datos de Airflow..."
        airflow db migrate

        echo "Creando usuario admin..."
        airflow users create \
          --username airflow \
          --password airflow \
          --firstname Admin \
          --lastname User \
          --role Admin \
          --email admin@example.com || true

        echo "Listo."
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: "SequentialExecutor"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "sqlite:////opt/airflow/airflow.db"
    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./:/opt/airflow/proyecto-ml        # ðŸ‘ˆ monta el proyecto con src incluido
    restart: "no"

  airflow-webserver:
    image: proyecto-ml-airflow:latest
    command: ["webserver"]
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    ports:
      - "8081:8080"
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: "SequentialExecutor"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "sqlite:////opt/airflow/airflow.db"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: always
    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./:/opt/airflow/proyecto-ml        # ðŸ‘ˆ aquÃ­ tambiÃ©n

  airflow-scheduler:
    image: proyecto-ml-airflow:latest
    command: ["scheduler"]
    depends_on:
      airflow-init:
        condition: service_completed_successfully
    environment:
      AIRFLOW_HOME: /opt/airflow
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__CORE__EXECUTOR: "SequentialExecutor"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "sqlite:////opt/airflow/airflow.db"
    restart: always
    volumes:
      - airflow_data:/opt/airflow
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./:/opt/airflow/proyecto-ml        # ðŸ‘ˆ y aquÃ­

networks:
  default:
    name: proyecto-ml_default
